from typing import List
from fastapi.testclient import TestClient
from app.routers.item_classification_router import (
    ClassifyItemsRequest,
    ClassifyItemsResponseDto,
    Item,
)
from main import app
import pytest

client = TestClient(app)


@pytest.mark.parametrize(
    "item_name, accounting_group, expected_type",
    [
        # PASS:
        # ("pizza", "food"),
        # ("coca-cola", "beverage"),
        # ("papa burger", "food"),
        # ("french fries", "food"),
        # ("coffee", "beverage"),
        # ("pasta", "food"),
        # ("tea", "beverage"),
        # ("pesto chicken", "food"),
        # ("Bloody mary", "beverage"),
        # ("nachos", "food"),
        # ("negroni", "beverage"),
        # ("mixed salad", "food"),
        # ("Big Blue moon", "beverage"),
        # ("chocolate cake", "food"),
        # ("Big Guiness", "beverage"),
        # ("bordeaux", "beverage"),
        # ("primitivo", "beverage"),
        # ("lambchops", "food"),
        # ("spaghetti", "food"),
        # ("Aberlour 12yr", "beverage"),
        # ("beverage", "beverage"),
        # ("food", "food"),
        # ("scaloppine di vitello con risotto", "food"),
        # -------------ITEMS (934163976814594): ------------
        # FAILED ON OPENAI chatcompletionapi:
        # ("Open Menu", "Misc", "Miscellaneous"),
        # ("Item note", "Misc", "Miscellaneous"),
        # ("Order note", "Misc", "Miscellaneous"),
        # ("Please wait", "Misc", "Miscellaneous"),
        # ("Important customer", "Misc", "Miscellaneous"),
        # ("Faster please", "Misc", "Miscellaneous"),
        # ("Test Item", "Misc", "Miscellaneous"),
        ("Vegetable Fritters (4pcs)", "Sides", "food"),
        ("Japchae", "Side", "food"),
        ("Korean Dumplings (5pcs)", "Sides", "food"),
        ("Kimchi", "Side", "food"),
        ("Water", "Drinks", "beverage"),
        ("Bubbly", "Drinks", "beverage"),
        ("Perrier", "Drinks", "beverage"),
        ("Soup + Kimchi", "food Modifiers", "food"),
        ("No Sauce", "Add ons", "food"),
        # ("Gochujang (Drizzle on top)", "Add ons", "food"), #fails here
        ("Doraji Signature", "Add ons", "food"),
        # ("Doraji Soy", "Add ons", "food"), #Not sure, fails local
        ("Miso Sesame Mayo", "Add ons", "food"),
        ("Ssamjang Mayo", "Add ons", "food"),
        ("Doraji BBQ", "Add ons", "food"),
        ("Make it a Combo", "food Modifiers", "food"),
        ("Extra Protein (Bibimbap)", "Add ons", "food"),
        ("White Rice (Default)", "Add ons", "food"),
        ("Purple Rice", "Add ons", "food"),
        ("Quinoa", "Add ons", "food"),
        ("No Carrots", "Add ons", "food"),
        ("No Beansprouts", "Add ons", "food"),
        ("No Radish", "Add ons", "food"),
        ("No Zucchini", "Add ons", "food"),
        ("No Spinach", "Add ons", "food"),
        ("No Doraji", "Add ons", "food"),
        ("No Shiitake Mushrooms", "Add ons", "food"),
        ("No Egg", "Add ons", "food"),
        ("No Sesame Oil", "Add ons", "food"),
        ("No Cabbage", "Add ons", "food"),
        ("No Kimchi", "Add ons", "food"),
        ("No Japchae", "Add ons", "food"),
        ("No Green Onions", "Add ons", "food"),
        ("No Onions", "Add ons", "food"),
        ("No Carrot", "Add ons", "food"),
        ("Coke", "Drinks", "beverage"),
        ("Diet Coke", "Drinks", "beverage"),
        ("Coke Zero", "Drinks", "beverage"),
        ("Ginger Ale", "Drinks", "beverage"),
        ("Teazle Grapefruit Black Tea", "Drinks", "beverage"),
        ("Teazle Lime & Mint Tea", "Drinks", "beverage"),
        ("Korean Plum Drink", "Drinks", "beverage"),
        ("Korean Barley Tea Drink", "Drinks", "beverage"),
        ("On the side", "Add ons", "food"),
        ("Miso Soup", "Side", "food"),
        ("Extra Egg", "Add ons", "food"),
        ("No Sesame Seeds", "Add ons", "food"),
        ("Half White Rice", "Add ons", "food"),
        ("Half Purple Rice", "Add ons", "food"),
        ("Half Quinoa", "Add ons", "food"),
        # -------------------------
        # #--------FAILED ON OPENAI chatcompletionapi and here
        # ("Divers", "Divers FROID", "Miscellaneous"),
        # ("Texte libre FROID", "Divers FROID", "Miscellaneous"),
        # ("Texte compte", "Divers FROID", "Miscellaneous"),
        # ("Attendre SVP", "Divers FROID", "Miscellaneous"),
        # ("Client VIP", "Divers FROID", "Miscellaneous"),
        # ("Accélérer SVP", "Divers FROID", "Miscellaneous"),
        # ("Supplément saumon", "Divers FROID", "Miscellaneous"),
        # ("Supplément avocat", "Divers FROID", "Miscellaneous"),
        # ("only sweet", "Divers CHAUD", "Miscellaneous"),
        # ("only potato", "Divers CHAUD", "Miscellaneous"),
        # ("Supplément poulet", "Divers FROID", "Miscellaneous"),
        # ("Supplement quinoa", "Divers FROID", "Miscellaneous"),
        # ("PDT + Sweet", "Divers CHAUD", "Miscellaneous"),
        # ("Spicy Mayo", "Divers FROID", "Miscellaneous"),
        # ("Carnitas Burger Perso", "Perso", "food"),
        # ("Atun Bowl Perso", "Perso", "food"),
        # ("Greens & Calabacin Perso", "Perso", "food"),
        # ("Potato Burger", "Perso", "food"),
        # ("TGMK Ceviche Perso", "Perso", "food"),
        # ------------------------
        # 172666275243780
        ("Choriqueso Empanada", "Entrées FROID", "food"),
        ("Sundried Tomatoes Empanada", "Entrées FROID", "food"),
        ("Guacamole", "Guacamole", "food"),
        ("Make It Spicy", "Guacamole", "food"),
        ("Quesadilla Veggie R2", "Sides FROID", "food"),
        ("Pollo Tacos", "Tacos", "food"),
        # ("Tigermilk Ceviche Specials", "Specials", "food"), #FAILS
        # ("Tigermilk Pudding", "Desserts", "food"), #fail
        ("Good Old Ceviche", "Specials", "food"),
        ("Cured Salmon", "Plats CHAUD", "food"),
        ("Tigeribs", "Plats CHAUD", "food"),
        ("Pollo Burger", "Plats CHAUD", "food"),
        ("Superbowl", "Plats FROID", "food"),
        ("Quinoa Bowl", "Plats FROID", "food"),
        ("Green But Not Boring", "Plats FROID", "food"),
        ("Wagyu Carpaccio", "Plats CHAUD", "food"),
        ("Mousse Choco", "Desserts", "food"),
        ("Tiramisu SV", "Desserts", "food"),
        ("Mangue & Yaourt", "Desserts", "food"),
        ("Maracuja Cheesecake", "Desserts", "food"),
        ("Chiffonade de Lomo", "Entrées FROID", "food"),
        ("Breakfast Quesadilla", "Entrées FROID", "food"),
        ("Patate Douce R2", "Entrées FROID", "food"),
        ("Not So Classic Avo Toast", "Entrées FROID", "food"),
        ("Avocado Toast œuf", "Entrées FROID", "food"),
        # ("Pacifico Toast", "Entrées FROID", "food"), #fails??
        ("Chilli Mango Avo Toast", "Entrées FROID", "food"),
        ("Acai Bowl", "Desserts", "food"),
        ("Horgelus verre", "Vin au verre", "beverage"),
        ("verre Carmenere Anderra 2016", "Vin au verre", "beverage"),
        ("Côtes de Gascogne - Verre", "Vin au verre", "beverage"),
        ("Verre Casa Nova rosé", "Vin au verre", "beverage"),
        ("Cotes de Gascogne Horgelus 2018", "Vin bouteille", "beverage"),
        ("Cotes du Rhône - Beaupré", "Vin bouteille", "beverage"),
        ("Malbec Perita Diamandes 2017", "Vin bouteille", "beverage"),
        ("Crozes Hermitage - Cave de Tain", "Vin bouteille", "beverage"),
        ("Cotes de Gascogne Pellehaut", "Vin bouteille", "beverage"),
        ("Tursan Carpediem 2017", "Vin bouteille", "beverage"),
        ("Vouvray Domaines des Aubuisières 2016", "Vin bouteille", "beverage"),
        ("1er Cru La Chablisienne", "Vin bouteille", "beverage"),
        ("Meurseault Aegerter 2017", "Vin bouteille", "beverage"),
        ("Gevrey Chambert Dom Gibourg 2016", "Vin bouteille", "beverage"),
        ("Hermitage Domaines de Montine 2017", "Vin bouteille", "beverage"),
        ("Lagrange 2011", "Vin bouteille", "beverage"),
        ("Champagne Brut Delamotte", "Vin bouteille", "beverage"),
        ("Casa Nova", "Vin bouteille", "beverage"),
        ("Pisco Sour Clasico", "Cocktails", "beverage"),
        ("Mezcal Margarita", "Cocktails", "beverage"),
        ("Fernet Negroni", "Cocktails", "beverage"),
        ("Pepper Gin Tonic", "Cocktails", "beverage"),
        ("Hot Mule", "Cocktails", "beverage"),
        ("San Miguel 25cl", "Biere Pression", "beverage"),
        ("San Miguel 50cl", "Biere Pression", "beverage"),
        ("Pacifico Clara Mexican Beer", "Biere Bouteille", "beverage"),
        ("Delta IPA", "Biere Bouteille", "beverage"),
        ("Charitea Black", "Softs", "beverage"),
        ("Charitea Red", "Softs", "beverage"),
        # ("Charitea Maté", "Softs", "beverage"),#fails on en model
        ("Charitea Green", "Softs", "beverage"),
        ("Coca Cola", "Softs", "beverage"),
        # ("Jus Pomme&Gingembre", "Softs", "beverage"), #fails on en model
        # ("Jus Pomme&Cerise", "Softs", "beverage"), #fails on en model
        ("Limonade", "Softs", "beverage"),
        ("Limonade au gingembre", "Softs", "beverage"),
        ("Espresso", "Café", "beverage"),
        ("Café allongé", "Café", "beverage"),
        ("Latte", "Café", "beverage"),
        ("Cappuccino", "Café", "beverage"),
        # FAILS ON EN model
        # ("Thé noir Earl Grey", "Thé", "beverage"),
        # ("Thé vert Chun Mee", "Thé", "beverage"),
        ("Thé Rooibos Earl Grey", "Thé", "beverage"),
        ("Infusion", "Thé", "beverage"),
        # ("Maté", "Thé", "beverage"),#fails on en model
        ("Eau plate", "Eaux", "beverage"),
        ("Eau gazeuse", "Eaux", "beverage"),
        ("Carmenere Anderra 2016", "Vin bouteille", "beverage"),
        ("Tigermilk ceviche plat", "Plats FROID", "food"),
        ("Virgin cocktail", "Cocktails", "beverage"),
        ("Café double", "Café", "beverage"),
        ("Decafeiné", "Café", "beverage"),
        # ("Jus Multifruits", "Softs", "beverage"), #fails on en model
        ("Espresso Martini", "Cocktails", "beverage"),
        ("Coca Zero", "Softs", "beverage"),
        ("Irish coffee", "Café", "beverage"),
        ("Bière Baby Lone", "Biere Bouteille", "beverage"),
        ("Bière Grosse Bertha", "Biere Bouteille", "beverage"),
        ("Ritual Kombucha", "Softs", "beverage"),
        ("Club Maté", "Softs", "beverage"),
        ("Jagermeister", "Alcools", "beverage"),
        ("Liqueur Acaï", "Alcools", "beverage"),
        ("Pastis Bardouin", "Alcools", "beverage"),
        ("Chartreuse Verte", "Alcools", "beverage"),
        ("Kahlua", "Alcools", "beverage"),
        # ("Suze", "Apéritifs", "beverage"), #fails on en model
        ("Cachaca Toqui", "Alcools", "beverage"),
        ("Rhum Sailor Jerry", "Alcools", "beverage"),
        ("Tequila Calle 23 Criollo", "Alcools", "beverage"),
        ("Cachaca Ypioca", "Alcools", "beverage"),
        ("Rhum Diplomatico Mantuano", "Alcools", "beverage"),
        ("Mezcal Elsenorio Reposado", "Alcools", "beverage"),
        ("Mezcal Elsenorio Joven", "Alcools", "beverage"),
        ("Tequila Altos Reposado", "Alcools", "beverage"),
        ("Rhum Appleton", "Alcools", "beverage"),
        ("Fernet-Branca Menta", "Alcools", "beverage"),
        ("Amaretto Disarono", "Alcools", "beverage"),
        ("Fernet Branca", "Alcools", "beverage"),
        ("Absinthe Pandor White", "Alcools", "beverage"),
        ("Whisky Toki Suntory", "Alcools", "beverage"),
        ("Vodka Grey Goose", "Alcools", "beverage"),
        ("Vodka Belvédère", "Alcools", "beverage"),
        ("Gin Bombay Original", "Alcools", "beverage"),
        ("Gin Hendrick's", "Alcools", "beverage"),
        ("Gin Bombay East", "Alcools", "beverage"),
        ("Gin Citadelle", "Alcools", "beverage"),
        ("Gin Bombay Saphire", "Alcools", "beverage"),
        ("Gin Bacur Botega", "Alcools", "beverage"),
        ("Gin Suntory Roku", "Alcools", "beverage"),
        ("Armagnac Milady VSOP", "Alcools", "beverage"),
        ("Pisco Waqar", "Alcools", "beverage"),
        ("Whisky Oban 14 ans", "Alcools", "beverage"),
        ("Whisky Lagavulin 16 ans", "Alcools", "beverage"),
        ("Whisky Tokinoka", "Alcools", "beverage"),
        ("Whisky Nikka Barrel 51", "Alcools", "beverage"),
        ("Whisky Aberlour 10 ans", "Alcools", "beverage"),
        ("Whisly Hudson Baby Bourbon", "Alcools", "beverage"),
        ("Whisky J. Daniels", "Alcools", "beverage"),
        ("Whisky Chivas 12 ans", "Alcools", "beverage"),
        ("Whisky Chivas Regal", "Alcools", "beverage"),
        ("Whisky JW Black Label", "Alcools", "beverage"),
        ("Whisky Kirin Fuji-Sanroku", "Alcools", "beverage"),
        ("Whisky Togouchi", "Alcools", "beverage"),
        ("Whisky Bellevoye Bleu", "Alcools", "beverage"),
        ("Choriqueso Nachos", "Entrées CHAUD", "food"),
        ("Quesa Cochinita R2", "Sides FROID", "food"),
        ("Pollo Tacos R2", "Sides CHAUD", "food"),
        ("Supp guacamole", "Sides CHAUD", "food"),
        ("Meal quinoa", "Specials", "food"),
        ("Patates Douces", "Sides CHAUD", "food"),
        ("Domaine Auzias 2017", "Vin bouteille", "beverage"),
        ("Lalande de Pomerol - Lamothe", "Vin bouteille", "beverage"),
        ("Maracolada", "Cocktail Sans Alcool", "beverage"),
        ("Auzias", "Vin bouteille", "beverage"),
        ("Limonade Yuzu", "Softs", "beverage"),
        ("Ginger Yuyu Limonade", "Cocktails", "beverage"),
        ("Limonade Yuzu maison", "Softs", "beverage"),
        # ("Oranges Pressées", "Softs", "beverage"), #fails
        ("Noisette", "Café", "beverage"),
        ("Ginger Yuzu Limonade", "Cocktail Sans Alcool", "beverage"),
        ("Golden Latte curcuma", "Thé", "beverage"),
        ("Chai Latte Brunch", "Café", "beverage"),
        ("Verre O Encanto da Vinha", "Vin au verre", "beverage"),
        ("O Encanto da Vinha 2018", "Vin bouteille", "beverage"),
        ("Mala Leche", "Cocktails", "beverage"),
        ("verre Auzias Chardonnay", "Vin au verre", "beverage"),
        ("Wagyu Tartare", "Plats CHAUD", "food"),
        ("Flower Sour", "Cocktails", "beverage"),
        ("Monjelada", "Cocktails", "beverage"),
        ("Frozen Verveina", "Cocktails", "beverage"),
        ("Kir", "Vin au verre", "beverage"),
        ("Superbowl Perso", "Perso", "food"),
        # failed here
        # ("Green Perso", "Perso", "food"),
        # ("Green Poulet Perso", "Perso", "food"),
        # ("Pollo Burger Perso", "Perso", "food"),
        ("Quinoa Bowl Perso", "Perso", "food"),
        ("Mezcal Oyenda", "Alcools", "beverage"),
        ("Cheesecake Entier", "Desserts", "food"),
        ("Pollo Cheeseburger", "Plats CHAUD", "food"),
        ("Winter Body Quesadilla", "Plats FROID", "food"),
        ("Make Quinoa Great Again", "Plats FROID", "food"),
        ("Tigermilk Ceviche", "Plats FROID", "food"),
        ("Salmon Cevichito", "Sides FROID", "food"),
        ("Sweet & Creamy Tacos", "Tacos", "food"),
        ("Cheese Nachos", "Sides CHAUD", "food"),
        # ("Roasted Sweet Potatoes", "Alcools", "beverage"), wrong accounting_group by merch
        ("Vecindad", "Alcools", "beverage"),
        ("Les Darons", "Vin bouteille", "beverage"),
        ("Verre Les Darons", "Vin au verre", "beverage"),
        ("Malbec Trivento", "Vin bouteille", "beverage"),
        ("Verre Malbec Trivento", "Vin au verre", "beverage"),
        ("Côtes-du-Rhône - verre", "Vin au verre", "beverage"),
        ("Ginca Tonic", "Cocktails", "beverage"),
        ("Punch Del Mar", "Cocktails", "beverage"),
        ("Paloma Caliente", "Cocktails", "beverage"),
        ("Shake Shakira Colada", "Cocktails", "beverage"),
        ("Frozen Mezcal Margarita", "Cocktails", "beverage"),
        ("Kiwi-Ginger", "Cocktail Sans Alcool", "beverage"),
        ("Mezcal Union", "Alcools", "beverage"),
        ("Get 27", "Alcools", "beverage"),
        ("Champagne Delamotte", "Vin bouteille", "beverage"),
        ("Limoncello Cellini", "Alcools", "beverage"),
        ("Pumpkin Spice Maté", "Cocktails", "beverage"),
        ("Mezcal Spritz", "Cocktails", "beverage"),
        ("Tortas Mexicaine", "Cuisine", "food"),
        ("Butternut Farcie", "Cuisine", "food"),
        ("Calaveras", "Cuisine", "food"),
        ("Quinoa Special", "Plats FROID", "food"),
        ("Eau de Vie", "Alcools", "beverage"),
        ("Quesadilla Perso", "Perso", "food"),
        ("Quinoa Poulet Perso", "Perso", "food"),
        ("Superbowl Poulet Perso", "Perso", "food"),
        ("Salmon Crudito", "Sides FROID", "food"),
        ("Atunbowl", "Plats FROID", "food"),
        ("Pollo Burger R2", "Plats CHAUD", "food"),
        ("Pulled Pork Burger", "Plats CHAUD", "food"),
        ("Greens & Calabacin", "Plats FROID", "food"),
        ("Pavlova", "Desserts", "food"),
        ("Sundae Dulce de Leche", "Desserts", "food"),
        ("Bière Blanche", "Biere Bouteille", "beverage"),
        ("Bière IPA", "Biere Bouteille", "beverage"),
        ("M de Minuty", "Vin bouteille", "beverage"),
        ("Caïpicabana", "Cocktails", "beverage"),
        ("Caïpi Grande", "Cocktails", "beverage"),
        ("Chili Boom Mule", "Cocktails", "beverage"),
        ("Margarita Loca", "Cocktails", "beverage"),
        ("Frozen Mezcal Mojito", "Cocktails", "beverage"),
        ("Lychee Daïquiri", "Cocktails", "beverage"),
        ("Bonito Bonito", "Cocktail Sans Alcool", "beverage"),
        ("Mocktail Mule", "Cocktail Sans Alcool", "beverage"),
        ("Mas Que Nada", "Cocktail Sans Alcool", "beverage"),
        ("Limonade Mandarine", "Softs", "beverage"),
        ("Mamita Blanche", "Biere Bouteille", "beverage"),
        ("Thé Glacé Maison", "Softs", "beverage"),
        ("Infusion Florale Glacée", "Softs", "beverage"),
        # ("Jus", "Softs", "beverage"),# failed on english model
        ("La Peña", "Vin bouteille", "beverage"),
        ("La Peña Verre", "Vin au verre", "beverage"),
        ("Malbec - Alto Sur", "Vin bouteille", "beverage"),
        ("Carménère - El Grano", "Vin bouteille", "beverage"),
        ("Malbec - Verre", "Vin au verre", "beverage"),
        ("Carménère - Verre", "Vin au verre", "beverage"),
        ("Crozes Hermitage Clairmont", "Vin bouteille", "beverage"),
        ("Alceno", "Vin bouteille", "beverage"),
        ("Alceno Verre", "Vin au verre", "beverage"),
        ("Pas Vu, Pas Pris", "Vin bouteille", "beverage"),
        ("Chardonnay - Pas Vu Pas Pris", "Vin au verre", "beverage"),
        ("Côte de Provence - Soléane", "Vin bouteille", "beverage"),
        ("Verre Dune", "Vin au verre", "beverage"),
        ("Chablis", "Vin bouteille", "beverage"),
        ("Mendoza", "Brunch Chaud", "food"),
        ("Dumbo", "Brunch Chaud", "food"),
        ("Venice", "Brunch Froid", "food"),
        ("Tijuana", "Brunch Froid", "food"),
        ("Ice Tea Brunch", "Softs", "beverage"),
        # ("Infusion Florale Brunch", "Softs", "beverage"), #failed
        ("Limonade Enfant", "Softs", "beverage"),
        ("Chablis verre", "Vin au verre", "beverage"),
        ("Minuty Verre", "Vin au verre", "beverage"),
        ("Spritz de Normandie", "Cocktails", "beverage"),
        ("Ristretto", "Café", "beverage"),
        ("Sans", "Plats CHAUD", "food"),
        ("Dulce de Leche Cheesecake", "Desserts", "food"),
        ("NACHOS R2", "Sides CHAUD", "food"),
        ("Carnitas Burger", "Plats CHAUD", "food"),
        ("Frida Calor Quinoa", "Plats FROID", "food"),
        ("Pablo Escobowl", "Plats CHAUD", "food"),
        ("Carne Asada C", "Plats CHAUD", "food"),
        ("Chule Conmigo", "Plats CHAUD", "food"),
        ("Mi Quesa es tu Quesa", "Plats FROID", "food"),
        ("I'm on a Date Quesadilla", "Plats FROID", "food"),
        ("Rollin in the Dips", "Guacamole", "food"),
        ("Cabo San Ceviche", "Sides FROID", "food"),
        ("Queso Fundido", "Sides CHAUD", "food"),
        ("Dulce de Leche Churros", "Desserts", "food"),
        ("Cheesecake R2", "Desserts", "food"),
        ("Margarita Lime Pie", "Desserts", "food"),
        ("Choco Loco", "Desserts", "food"),
        ("Bourgogne Hautes-Côtes de Nuits", "Vin bouteille", "beverage"),
        ("GINCAmomilla", "Cocktails", "beverage"),
        ("Isabela Sour", "Cocktails", "beverage"),
        ("Margarita Latina", "Cocktails", "beverage"),
        ("Copita Mezcal Union", "Spirits", "beverage"),
        ("Pichet Mezcal Union", "Spirits", "beverage"),
        ("Copita Mezcal Koch Espadin", "Spirits", "beverage"),
    ],
)
def test_item_classification(item_name, accounting_group, expected_type):
    req_body = ClassifyItemsRequest(
        items=[Item(item_name=item_name, accounting_group=accounting_group)]
    )
    json_req = req_body.model_dump_json()
    response = client.post("/api/classify-items", data=json_req)
    assert response.status_code == 200

    response_data: List[ClassifyItemsResponseDto] = response.json()
    # only doing 1 at a time
    if response_data[0]["food_score"] > response_data[0]["beverage_score"]:
        classified_as = "food"
    else:
        classified_as = "beverage"

    assert (
        classified_as == expected_type
    ), f"{item_name} was classified a {classified_as} but I expected {expected_type}"
